### ISSUE TITLE
TypeError: boxrec.login is not a function

### ISSUE THREAD

**Issue by ravibadoni** [boxing/boxrec#118]
const boxrec = require("boxrec");

boxrec.login('ravib', 'rb123456')
.then(() => {
console.log("111111");
    // successfully logged in
})
.catch(error => {});

this shows

TypeError: boxrec.login is not a function
    at Object.<anonymous> (H:\boxrec\test\index.js:3:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

**Comment by mikedidomizio** [comment]
Hey there,

Sorry the docs need updating, what you're looking for is:

```
const boxrec = require("boxrec").default; // is a default export
console.log(boxrec.login); // function
```

In version 2.0 it won't be a default export, and will be accessible like:

```
const {Boxrec} = require("boxrec");
console.log(Boxrec.login);
```

Anyways let me know if that works for you

**Comment by ravibadoni** [comment]
thank you for replying.
can you please share any updated doc or updated version please

**Comment by mikedidomizio** [comment]
So if you console log the imported class you might see some strange stuff like that.  What happens is when you make a request like:

`const floydMayweather = await boxrec.getPersonById(352);`

the `floydMayweather` class variable stores the HTML inside it and only parses things as you request them.

`console.log(floydMayweather.name)` // output: Floyd Mayweather Jr

so when you call `.name`, the getter parsed the HTML and returns the name.  The name is never stored as a variable.

In future versions there _should_ be a way to get the entire JSON object all at once, which is probably what you want but right now this is the way it works.

It's not perfect but there should be enough documentation to get you started.  For example this link https://github.com/boxing/boxrec#getpersonbyid shows you a bunch of the other getters after using `getPersonById`.

**Comment by mikedidomizio** [comment]
I've updated the [README](https://github.com/boxing/boxrec) to match what's currently being published at this time.  I'm going to close this issue at this time.  If you have major questions/issues feel free to re-open this issue or create a new one.
