### ISSUE TITLE
Unable to login to boxrec

### ISSUE THREAD

**Issue by yjnsrc** [boxing/boxrec#189]
I keep getting this error when trying to login to the boxrec API:
`Error: Could not get cookie from initial request to boxrec`

This is my code: 
```
var username = process.env.BOXREC_USER;
var password = process.env.BOXREC_PASSWORD;
try {
    const cookieJar = await boxrec_1.default.login(username, password);
} catch (e) {
    console.log("An error: " + e);
}
```
Your help would be very much appreciated.

**Comment by mikedidomizio** [comment]
Are you importing the package via:
`const boxrec = require("boxrec").Boxrec;`

Although it might not make a difference, is the `await` inside an `async`?

try this below:
```
(async function () {
    try {
        const cookieJar = await boxrec.login(username, password);
    } catch(e) {
        console.log("An error: " + e);
    }
})();
```

**Comment by yjnsrc** [comment]
Thank you for responding @mikedidomizio.

This is what I'm doing now, but I'm getting the same error. 

```
const boxrec = require("boxrec").default;
console.log(boxrec);

(async function run() {
    try {
        const cookieJar = await boxrec.login("USER", "PASS");
    } catch(e) {
        console.log("An error: " + e);
    }
})();
```

**Comment by mikedidomizio** [comment]
Can you also run an `npm install boxrec@^5.0.2` or `yarn add boxrec@^5.0.2`?  There was an update in 5.0.X as the logging into BoxRec has changed

**Comment by yjnsrc** [comment]
Thank you, this resolved my issue.
