### ISSUE TITLE
getSchedule returning null data

### ISSUE THREAD

**Issue by sidraval** [boxing/boxrec#226]
Hello,

First off, thanks for building this - it's rad!

I'm getting some confusing behavior when calling `boxrec.getSchedule`. With the following code:

```typescript
/* const cookieJar = ... */
const schedule = await boxrec.getSchedule(cookieJar, {
    countryCode: Country.USA
});

schedule.events.forEach((bpe) => {
    console.log(bpe.date)
    bpe.bouts.forEach((bout) => {
        console.log(bout.firstBoxer)
        console.log(bout.rating);
    })
})
```

I get the following output (abbreviated):
```
2019-11-01
{ id: null, name: null }
null
{ id: null, name: null }
null
{ id: null, name: null }
null
{ id: null, name: null }
```

~~I'm not exactly sure why this is happening, but I noticed while looking through [the documentation](https://boxrec-npm-docs.s3.us-east-2.amazonaws.com/master/classes/boxrecpageschedule.html), it looks like the `getSchedule` function would make a call to the following page: https://boxrec.com/en/schedule?c[countryCode]=US~~

~~But when I browse to the page directly, the URL I see is https://boxrec.com/en/schedule?utQ[countryCode]=US~~

~~Which might have something to do with it?~~

**Comment by sidraval** [comment]
Ah, upgrading from `7.0.0` to `7.0.1` fixed (most?) of this. Now the same code above produces this output:

```
2019-11-01
{ id: 827958, name: 'Hakim Lopez' }
null
{ id: 572090, name: 'Angel Luna' }
null
{ id: 867627, name: 'Arturs Ahmetovs' }
null
{ id: 746282, name: 'Glenn Hagler Jr' }
null
{ id: 784475, name: 'Richard Rivera' }
null
```

The `bout.rating` logs are still `null`, is that expected?

**Comment by mikedidomizio** [comment]
Update to [7.0.2](https://github.com/boxing/boxrec/pull/229) and let me know if that fixes your issue

**Comment by sidraval** [comment]
It does indeed, thanks!
