### ISSUE TITLE
Have to manually import Country enum

### ISSUE THREAD

**Issue by sidraval** [boxing/boxrec#227]
Hello,

The following code produces a typescript error, `Cannot find name 'Country'.`

```typescript
import { Boxrec as boxrec } from "boxrec";

const schedule = await boxrec.getSchedule(cookieJar, {
        countryCode: Country.USA
});
```

Adding the following import makes it work:

```typescript
import { Country } from "boxrec/dist/boxrec-pages/location/people/boxrec.location.people.constants";
```

Is that expected?

**Comment by mikedidomizio** [comment]
For the time being this is probably the best way of doing it.  I still have to implement a better way of managing these interfaces/types

**Comment by mikedidomizio** [comment]
This has been fixed now and you should be able to import `Country` from the `boxrec` package.  Closing this issue.

```typescript
import {Boxrec, Country} from "boxrec";
```
