### ISSUE TITLE
Cannot get round GDPR error

### ISSUE THREAD

**Issue by abienz** [boxing/boxrec#241]
When I make a request via the API I am given the Error

`Error: GDPR consent is needed with this account. Log into BoxRec through their websiet and accept before using this account`

I then go to the Boxrec website and try and give consent I am in the EU, I have tried removing all cookies, and when I reload the site I am given the option to accept or reject cookies, no matter if I accept all, reject all, or any combination I cannot get around the error.

Here is my code:
```
const boxrec = require('boxrec').Boxrec

const BOXREC_USERNAME = '******'
const BOXREC_PASSWORD = '******'

async function getBoxer() {
    try {
        const cookieJar = await boxrec.login(BOXREC_USERNAME, BOXREC_PASSWORD)
        const boxer = boxrec.getPersonById(cookieJar, 352)
        console.log(boxer)
    }
    catch (e) {
        console.log(e)
    }
}

getBoxer()
```

**Comment by rubengmurray** [comment]
Getting exactly the same @abienz. Looked everywhere on the Boxrec site & forums and can't see where I can approve to remove the error.

**Comment by mikedidomizio** [comment]
All right, I'll try it out myself

**Comment by mikedidomizio** [comment]
Resolved in pull request https://github.com/boxing/boxrec/pull/242

Update to `7.1.1`

**Comment by abienz** [comment]
Appears to work for me now, many thanks.

**Comment by rubengmurray** [comment]
That fixed the issue. Cheers @mikedidomizio
