### ISSUE TITLE
Data came in strange format

### ISSUE THREAD

**Issue by lyudad** [boxing/boxrec#247]
<img width="509" alt="Снимок экрана 2020-08-12 в 15 34 10" src="https://user-images.githubusercontent.com/25103090/90015446-4a2ce600-dcb1-11ea-84c8-6f771a2629dd.png">

this is my code, I just copy past it from instruction

<img width="657" alt="Снимок экрана 2020-08-12 в 15 32 42" src="https://user-images.githubusercontent.com/25103090/90015485-587b0200-dcb1-11ea-8879-2848ebe15bfd.png">
this is what I have in console

I have not found similar issue and can't understand what I'm doing wrong

**Comment by mikedidomizio** [comment]
Hey, 

The returned object from API requests is a CheerioJS object.  The reason was for speed purposes, sometimes we don't necessarily need all the data of a boxer.  One of the cons of this is that you can't `console.log` the entire output easily. 

If you plan on sending JSON to the UI, I'd probably do it like this

```
const boxerResults = await boxrec.getPersonById(356831);

// destructure the accessor values
const boxer = {
    name,
    division,
    // ...
} = boxerResults;

// send as JSON object
res.json(boxer);
```

Hope this helps

**Comment by mikedidomizio** [comment]
I forgot, you can also use `output` I believe, which returns a JSON object.
```
const boxerResults = await boxrec.getPersonById(356831);
console.log(boxerResults.output);
```

**Comment by lyudad** [comment]
Thank you for response, but it was not helped. As you can see in both cases I have `Cannot read property 'name' of undefined`
<img width="682" alt="Снимок экрана 2020-09-02 в 00 10 58" src="https://user-images.githubusercontent.com/25103090/91906617-29085580-ecb1-11ea-9859-305f045900dc.png">


<img width="720" alt="Снимок экрана 2020-09-02 в 00 12 48" src="https://user-images.githubusercontent.com/25103090/91906609-273e9200-ecb1-11ea-8180-3805f053a8f9.png">

**Comment by mikedidomizio** [comment]
Sorry for not getting back to you sooner.  I think I see the issue.  Maybe the documentation you read was incorrect.  The first param of `getPersonById` is the `cookieJar`.  What that is is the cookie of your logged in session of BoxRec.  Perhaps it could use more information if the params aren't all set.

Try this:

```
// as always do not commit these two lines.  Use environment variables or read from some temp file that doesn't get committed
 const boxrecUsername = "YOUR_USERNAME",
        boxrecPassword = "YOUR_PASSWORD";

    try {
         // we first log into boxrec with our credentials
        const cookieJar = await boxrec.login(boxrecUsername, boxrecPassword);
        // we pass the cookie along with the boxer ID that we want to retrieve
        const floydMayweather = await boxrec.getPersonById(cookieJar, 352);
        console.log(floydMayweather.name);
        console.log(floydMayweather.output);
    } catch (e) {
        console.log("this failed", e)
    }
```

I hope that works for you!

**Comment by mikedidomizio** [comment]
Closing this at this time due to no response
