### ISSUE TITLE
Uncaught TypeError TypeError: $ is not a function When trying to get "output" or "links"

### ISSUE THREAD

**Issue by FelixFreelancer** [boxing/boxrec#286]
Hi @mikedidomizio 
I really appreciated your effort to upgrade this package continuously.

Btw, I found this error when I tried to get `"output"` or `"links"` field.

This is my code.
```
let schedules = await boxrec.getSchedule(cookieJar, {
    countryCode: '',
});
console.log(schedules.events[0].bouts[0].links);

... OR

let schedules = await boxrec.getDate(cookieJar, {
    day: 19,
    month: 4,
    year: 2022
});
console.log(schedules.output.events[0].bouts[0].output);
```

And when I try to access to the "links" or "output" field to get `bout_id` like above ones, it just gives this error for some reason.
I was able to access to them in the previous version but they were just `null` for some reason.
```
Uncaught TypeError TypeError: $ is not a function
    at o.parseLinksColumn (c:\boxrec\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:353)
    at <anonymous> (c:\boxrec\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:243)
    at each (c:\boxrec\node_modules\cheerio\lib\api\traversing.js:480:26)
    at o.parseLinkInformation (c:\boxrec\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:216)
    at get (c:\boxrec\node_modules\boxrec\dist\boxrec-pages\event\boxrec.page.event.bout.row.js:1:2308)
...
```
Not sure If I will need to install another package with `boxrec` package.

Could you please check this issue?
Thanks

**Comment by mikedidomizio** [comment]
Can you double check that you're using 8.0.0? I merged a [PR](https://github.com/boxing/boxrec/pull/287) that adds E2E tests for both `links.bio` and `links.bout` that should cover what you sent above - `getDate` and `getSchedule`.  

Although I did forget to add a test for the `output` of `getSchedule`, I did run it to see the output.  It didn't blow up although it could be better.  It does return the links.

<img width="677" alt="image" src="https://user-images.githubusercontent.com/5728044/164333856-fecf179f-df6c-4ca4-ad79-442ea1be6f62.png">

There may be something I'm missing though so I'll wait for your feedback.  Thank you for the detailed description.  It definitely saves time if I know the request, response or error, etc.

**Comment by FelixFreelancer** [comment]
Thanks for your checking the issue.

This is my code I just tested with.

```
let schedules = await boxrec.getDate(cookieJar, {
      day: 21,
      month: 4,
      year: 2022
 });
```
 
 And the response is like this. 
![image](https://user-images.githubusercontent.com/40544276/164358035-464bf9c3-29a9-4395-bdd3-358b1d27878a.png)

And then I tried to get the first bout of the first event.
`schedules.events[0].bouts[0]`

![image](https://user-images.githubusercontent.com/40544276/164358211-489533a2-c372-4dd8-8da3-fce3e83debe5.png)

Lastly I tried to get the output of the bout, then it throws this error.
`schedules.events[0].bouts[0].output`

```
Uncaught TypeError TypeError: $ is not a function
    at o.parseLinksColumn (c:\boxrec\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:353)
    at <anonymous> (c:\boxrec\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:243)
    at each (c:\boxrec\node_modules\cheerio\lib\api\traversing.js:480:26)
    at o.parseLinkInformation (c:\boxrec\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:216)
    ....
```

I also confirmed I am using the latest version(8.0.0).

Thanks

**Comment by FelixFreelancer** [comment]
Hi @mikedidomizio 
Have you had time to check the issue?
Should I also send the response of `getSchedule` function so you can see what is the issue easily?

Thanks

**Comment by mikedidomizio** [comment]
No ETA since last time, I have been busy.  Any more information is helpful.

**Comment by FelixFreelancer** [comment]
HI @mikedidomizio 

Could you please let me know if you had a look at this issue?
Please just take a look at the `getDate()` function to get the `bout ID`.
It still gives the same issue unfortunately.

Thanks

**Comment by mikedidomizio** [comment]
I haven't had time to look at it.  Will comment here when there is an update.

**Comment by mikedidomizio** [comment]
I published [8.0.1](https://github.com/boxing/boxrec/pull/288), that I hope addresses the problem.

This was my testing script, and perhaps in the future I'll ask for the script beforehand.

```
const {Boxrec} = require("boxrec");

(async() => {
    try {
        const cookie = await Boxrec.login(process.env.BOXREC_USERNAME, process.env.BOXREC_PASSWORD);

        let schedules = await Boxrec.getSchedule(cookie, {
            countryCode: '',
        });
        console.log(schedules.events[0].bouts[0].links);

        let schedules2 = await Boxrec.getDate(cookie, {
            day: 19,
            month: 4,
            year: 2022
        });
        console.log(schedules2.output.events[0].bouts[0].output);

        console.log('done')
    } catch(e) {
        console.log(e)
    }
})();
```

this was the after output (good links)

```
{ bio: 2832562, bout: '853786/2832562', other: [] }
{
  division: 'welterweight',
  firstBoxer: { id: 1086023, name: 'Kagan Kanlibilge' },
  firstBoxerLast6: [],
  firstBoxerRecord: { draw: 0, loss: 0, win: 0 },
  firstBoxerWeight: null,
  links: { bio: 2831984, bout: '853662/2831984', other: [] },
  metadata: '2022 EUBC European Youth Championships Quarter-Final\n<br>',
  numberOfRounds: [ 3, 3 ],
  outcome: 'win',
  outcomeByWayOf: 'SD',
  rating: 20,
  secondBoxer: { id: 1066608, name: 'Jim Donovan' },
  secondBoxerLast6: [ 'win', 'win', 'win', 'win', 'win', 'win' ],
  secondBoxerRecord: { draw: 0, loss: 1, win: 9 },
  secondBoxerWeight: null,
  sport: 'am boxing'
}
done
```


Otherwise if this doesn't fix it send me the exact script and expected outputs.  Anything else as well.

Then wait.

**Comment by mikedidomizio** [comment]
I never experienced the Cheerio errors you experienced.  Which is weird.

If you still experience errors, give me whatever script you're using.

**Comment by FelixFreelancer** [comment]
Hi @mikedidomizio 

Thanks for the updates.
But it still doesn't appear working.

I made a very simple script as it still gave the errors on my old code.
This is my simple script.

```
const boxrec = require("boxrec").Boxrec;

(async() => {
    try {
        const BOXREC_USERNAME = process.env.BOXREC_USERNAME;
        const BOXREC_PASSWORD = process.env.BOXREC_PASSWORD;
        const cookie = await boxrec.login(BOXREC_USERNAME, BOXREC_PASSWORD);

        let schedules = await boxrec.getSchedule(cookie, {
            countryCode: '',
        });
        console.log(schedules.events[0].bouts[0].links);

        let schedules2 = await boxrec.getDate(cookie, {
            day: 19,
            month: 4,
            year: 2022
        });
        console.log(schedules2.output.events[0].bouts[0].output);

        console.log('done')
    } catch(e) {
        console.log(e)
    }
})();
```

And this is my package.json
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "boxrec": "^8.0.1",
    "form-data": "^4.0.0"
  }
}
```
Please note that I also installed `form-data` package because it gave an error (`Cannot find module form-data`) when I installed only the `boxrec` package.

When I run the code, I can still see this error.
```
TypeError: $ is not a function
    at Function.o.parseLinksColumn (C:\test\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:353)
    at Node.<anonymous> (C:\test\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:243)
    at LoadedCheerio.each (C:\test\node_modules\cheerio\lib\api\traversing.js:480:26)
    at Function.o.parseLinkInformation (C:\test\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:216)
    at e.get [as links] (C:\test\node_modules\boxrec\dist\boxrec-pages\event\boxrec.page.event.bout.row.js:1:2308)
    at C:\test\index.js:12:50
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Thanks

**Comment by mikedidomizio** [comment]
Your script worked fine 🤔.

Can you delete the `node_modules` directory and do a clean install.  Maybe even `npm cache clean` for good measures?

What version of Node are you using? (I'm currently on 16.13.2)

As for the form-data error, can you share whatever the full error is?  The project has no peer dependencies and I've never seen it.  It does have dependencies that do rely on it, but that shouldn't affect this project.

Thanks

**Comment by FelixFreelancer** [comment]
Sorry for the late response.

I am currently using the latest Node Version (16.14.0)
And I also cleaned the cache as you suggested.

I installed only the latest Boxrec package(8.0.1) and tried to run the same code above.
But I can't even run the code due to this error.

```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'form-data'
Require stack:
- C:\test\node_modules\boxrec-requests\dist\boxrec-requests.js
- C:\test\node_modules\boxrec-requests\dist\index.js
- C:\test\node_modules\boxrec\dist\boxrec.class.js
- C:\test\node_modules\boxrec\dist\index.js
- C:\test\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\test\node_modules\boxrec-requests\dist\boxrec-requests.js:41:16)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\test\\node_modules\\boxrec-requests\\dist\\boxrec-requests.js',
    'C:\\test\\node_modules\\boxrec-requests\\dist\\index.js',
    'C:\\test\\node_modules\\boxrec\\dist\\boxrec.class.js',
    'C:\\test\\node_modules\\boxrec\\dist\\index.js',
    'C:\\test\\index.js'
  ]
}
```

Thanks

**Comment by mikedidomizio** [comment]
Hey there,

Can you try `boxrec@8.0.2`?  I've added `form-data` to `boxrec-requests`.  I think it appeared fine to me but was actually a problem.

**Comment by FelixFreelancer** [comment]
The form-data module issue was disappeared.
But I can still see the same issue like the followings.

```
TypeError: $ is not a function
    at Function.o.parseLinksColumn (E:\test\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:353)
    at Element.<anonymous> (E:\test\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:243)
    at LoadedCheerio.each (E:\test\node_modules\cheerio\lib\api\traversing.js:519:26)
    at Function.o.parseLinkInformation (E:\test\node_modules\boxrec\dist\boxrec-common-tables\boxrec-common-links.js:1:216)
    at e.get [as links] (E:\test\node_modules\boxrec\dist\boxrec-pages\event\boxrec.page.event.bout.row.js:1:2308)
    at E:\test\index.js:12:50
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Thanks

**Comment by mikedidomizio** [comment]
Let's try boxrec@8.0.3.  I think it was the way CheerioJS was imported for that file and not loaded like the others.  It doesn't explain why it worked for me and not for you but I'm hoping this gets us past the problem you're seeing.

**Comment by FelixFreelancer** [comment]
Great
It worked as a charm.

Thank you very much
