### ISSUE TITLE
Location is always empty under bouts

### ISSUE THREAD

**Issue by FelixFreelancer** [boxing/boxrec#296]
Hi @mikedidomizio 

I am trying to get a location of a bout for each player.

This is my code.

```
let response = await boxrec.getPersonById(cookieJar, 644435);
let location = response.output.bouts[0].location;
```

The `location` is always `null` no matter what bout I check.
But I can see the valid location populated on  boxrec.com.

Could you please check this issue?

**Comment by mikedidomizio** [comment]
Released `boxrec@8.0.5` which should fix this issue.
