### ISSUE TITLE
Empty response for `search`

### ISSUE THREAD

**Issue by eawer** [boxing/boxrec#81]
For some reason I get empty responses while trying to make `search` or `getPeopleByName` call:

```js
const boxrec = require("boxrec");

(async () => {
    await boxrec.login(login, password);

    const results = await boxrec.search({
        first_name: 'floyd',
        last_name: 'mayweather',
    });
    console.log(results);
})();
```

Output: `[]`

No errors/warnings are thrown.
Other methods seem to work as expected

**Comment by mikedidomizio** [comment]
Hey,

So the parameters changed on BoxRec's end, therefore breaking this method.  I've made the changes and merged to master [here](https://github.com/boxing/boxrec/pull/82).

If you upgrade to version `0.18.2`, the search method should now work.
