### ISSUE TITLE
secondBoxer is not parsed as expected in getSchedule

### ISSUE THREAD

**Issue by eawer** [boxing/boxrec#83]
The example shows results for Oct 15, 2018, but the same is true for all other dates (bout - http://boxrec.com/en/event/774915/2277941):
```js
const boxrec = require("boxrec");

(async () => {
    await boxrec.login(login, password);
    const result = await boxrec.getSchedule();
    const bout = result.events[0].bouts[0];
    console.log('_firstBoxer:', bout._firstBoxer);
    console.log('_secondBoxer:', bout._secondBoxer);
    console.log('firstBoxer:', bout.firstBoxer);
    console.log('secondBoxer:', bout.secondBoxer);
})();
```
Output:
```
_firstBoxer:   <a href="/en/boxer/649120" class="personLink">Josemir Poulino</a><div class="mob"><span class="textWon">8</span>&#xA0;<span class="textLost">3</span>&#xA0;<span class="textDraw">0</span>
</div>
_secondBoxer:   Gino Kanters4 2 0

firstBoxer: { id: 649120, name: 'Josemir Poulino' }
secondBoxer: { id: null, name: null }
```

I suppose this is because `_secondBoxer` does not contain any markup for some reason

**Comment by mikedidomizio** [comment]
Yeah, it was stripping out the markup instead of keeping it.
This should be fixed now in this [pull request](https://github.com/boxing/boxrec/pull/85).

![image](https://user-images.githubusercontent.com/5728044/47126398-68149580-d256-11e8-9f98-3afdda249ced.png)

Upgrade to version **0.18.3**
