### ISSUE TITLE
does it work w/ browserify?

### ISSUE THREAD

**Issue by johnnyp77** [boxing/boxrec#88]
tried it boxrec seems to be blocking browser connection. hoping to get your input thank you.

**Comment by mikedidomizio** [comment]
Hey @johnnyp77,

It was designed with server side javascript in mind, not via the browser.  Is there a specific error it gives you?  Possibly CORS issue?  
I think it's more of an issue with that and not an issue with browserify itself

**Comment by mikedidomizio** [comment]
Closing the issue for the time being.  If there's more to add to this, feel free to re-open or create a new ticket.

Thanks
